apiVersion: integreatly.org/v1beta1
kind: GrafanaDataSource
metadata:
  name: prometheus-datasource
spec:
  datasources:
    - access: proxy
      editable: true
      isDefault: true
      jsonData:
        timeInterval: 5s
      name: Prometheus
      type: prometheus
      url: 'http://prometheus-service:9090'
      version: 1
  name: grafana-datasources.yaml